### PR TITLE
Added script version for python 3

### PR DESCRIPTION
**Pull request by fbarresi**

### CODE REVIEW

**Comment by fbarresi** [comment]
That's sadly not possible... urllib import and function are not compatible.

**Comment by jonbgallant** [comment]
Can you please modify device-conf instead of deleting it?

**Comment by fbarresi** [comment]
Oh, I'm sorry... I just tried tipping through my phone, and it's pretty hard... I'll do it better this night :)

**Comment by jonbgallant** [comment]
Can you test on both python2 and 3?

I get this when I run python device-conf in your fork..

`python: can't open file 'device-conf.py': [Errno 2] No such file or directory
`

**Comment by jonbgallant** [comment]
I see, you renamed to device-config instead of device-conf and I didn't notice that.  I'm working on fixing it up.

**Comment by jonbgallant** [comment]
Thanks for getting this started.  I have updated master with python3 support.

**Pull request closed without merging**
